package com.phi.pk;

import java.io.FileOutputStream;

import org.apache.log4j.Logger;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.intercept.BypassInterceptors;
 
@Name("mockPDFFileSaver")
@BypassInterceptors
public class MockPDFFileSaver {
 
 private static final Logger log = Logger.getLogger(MockPDFFileSaver.class);
	
 @In(create = true)
 PdfExporter pdfExporter;
 
 /**
  * Saves the PDF generated by the pageName to the file denoted by the
  * fileName
  *
  * @param fileName
  *            the file name
  * @param pageName
  *            the page name
  */
 public void saveOnFS(String fileName, String pageName, String cid) {
  byte[] pdfBytes = pdfExporter.pdfExport(pageName,cid, true);
  try {
   FileOutputStream fos = new FileOutputStream(fileName);
 
   fos.write(pdfBytes);
 
   fos.close();
  } catch (Exception e) {
   e.printStackTrace();
  }
 }
 
}