--BONIFICA PRATICHE VI_AZ che non hanno impostato correttamente pratiche_riferimenti

update pratiche_riferimenti set riferimento_ditta_id=5488, riferimento_sede_id=5696	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10831;
update pratiche_riferimenti set riferimento_ditta_id=5550, riferimento_sede_id=6133	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10925;
update pratiche_riferimenti set riferimento_ditta_id=5560, riferimento_sede_id=6187	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10864;
update pratiche_riferimenti set riferimento_ditta_id=5646, riferimento_sede_id=6413	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10868;
update pratiche_riferimenti set riferimento_ditta_id=5666, riferimento_sede_id=6462	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10999;
update pratiche_riferimenti set riferimento_ditta_id=5696, riferimento_sede_id=6537	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11011;
update pratiche_riferimenti set riferimento_ditta_id=5730, riferimento_sede_id=6653	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11024;
update pratiche_riferimenti set riferimento_ditta_id=5752, riferimento_sede_id=6816	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11036;
update pratiche_riferimenti set riferimento_ditta_id=5775, riferimento_sede_id=6871	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11016;
update pratiche_riferimenti set riferimento_ditta_id=5777, riferimento_sede_id=6902	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11066;
update pratiche_riferimenti set riferimento_ditta_id=5831, riferimento_sede_id=7189	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11139;
update pratiche_riferimenti set riferimento_ditta_id=5843, riferimento_sede_id=7214	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10882;
update pratiche_riferimenti set riferimento_ditta_id=5869, riferimento_sede_id=7371	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11198;
update pratiche_riferimenti set riferimento_ditta_id=5929, riferimento_sede_id=8807	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10981;
update pratiche_riferimenti set riferimento_ditta_id=5973, riferimento_sede_id=8927	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11136;
update pratiche_riferimenti set riferimento_ditta_id=5974, riferimento_sede_id=8930	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11000;
update pratiche_riferimenti set riferimento_ditta_id=5980, riferimento_sede_id=8948	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11042;
update pratiche_riferimenti set riferimento_ditta_id=5981, riferimento_sede_id=8949	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11260;
update pratiche_riferimenti set riferimento_ditta_id=5985, riferimento_sede_id=8958	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10858;
update pratiche_riferimenti set riferimento_ditta_id=5989, riferimento_sede_id=9182	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11284;
update pratiche_riferimenti set riferimento_ditta_id=6019, riferimento_sede_id=9353	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10883;
update pratiche_riferimenti set riferimento_ditta_id=6033, riferimento_sede_id=9416	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11323;
update pratiche_riferimenti set riferimento_ditta_id=6059, riferimento_sede_id=9515	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11302;
update pratiche_riferimenti set riferimento_ditta_id=6086, riferimento_sede_id=9595	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11361;
update pratiche_riferimenti set riferimento_ditta_id=6094, riferimento_sede_id=9635	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11360;
update pratiche_riferimenti set riferimento_ditta_id=6103, riferimento_sede_id=9679	, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11135;
update pratiche_riferimenti set riferimento_ditta_id=6143, riferimento_sede_id=10081, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10840;
update pratiche_riferimenti set riferimento_ditta_id=6200, riferimento_sede_id=10615, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11378;
update pratiche_riferimenti set riferimento_ditta_id=6216, riferimento_sede_id=10657, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11459;
update pratiche_riferimenti set riferimento_ditta_id=6220, riferimento_sede_id=10671, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11379;
update pratiche_riferimenti set riferimento_ditta_id=6240, riferimento_sede_id=10724, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10830;
update pratiche_riferimenti set riferimento_ditta_id=6261, riferimento_sede_id=10772, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10885;
update pratiche_riferimenti set riferimento_ditta_id=6262, riferimento_sede_id=10775, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10885;
update pratiche_riferimenti set riferimento_ditta_id=6277, riferimento_sede_id=10843, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11543;
update pratiche_riferimenti set riferimento_ditta_id=6277, riferimento_sede_id=10843, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11549;
update pratiche_riferimenti set riferimento_ditta_id=6314, riferimento_sede_id=11144, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10931;
update pratiche_riferimenti set riferimento_ditta_id=6392, riferimento_sede_id=11816, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11648;
update pratiche_riferimenti set riferimento_ditta_id=6491, riferimento_sede_id=12691, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11695;
update pratiche_riferimenti set riferimento_ditta_id=6542, riferimento_sede_id=12907, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10996;
update pratiche_riferimenti set riferimento_ditta_id=6599, riferimento_sede_id=13158, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11274;
update pratiche_riferimenti set riferimento_ditta_id=6712, riferimento_sede_id=13776, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10995;
update pratiche_riferimenti set riferimento_ditta_id=6739, riferimento_sede_id=14035, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11006;
update pratiche_riferimenti set riferimento_ditta_id=6952, riferimento_sede_id=15430, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10933;
update pratiche_riferimenti set riferimento_ditta_id=7238, riferimento_sede_id=16555, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=11453;
update pratiche_riferimenti set riferimento_ditta_id=7423, riferimento_sede_id=17204, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10977;
update pratiche_riferimenti set riferimento_ditta_id=7663, riferimento_sede_id=18638, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=10881;
update pratiche_riferimenti set riferimento_ditta_id=8042, riferimento_sede_id=NULL,  riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=12555;
update pratiche_riferimenti set riferimento_ditta_id=232,  riferimento_sede_id=233,   riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=12498;
update pratiche_riferimenti set riferimento_ditta_id=8152, riferimento_sede_id=28666, riferimento='phidic.spisal.segnalazioni.targetsource.ditta_V0' where internal_id=12638;