INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81.2019.5.1.26587_V0', 'Modified by hand in Dictionary', '26587163', 'phi-dev', 0, 'Obblighi del datore di lavoro', '163 - 1 - - Obblighi del datore di lavoro', NULL, NULL, NULL, NULL, 'Legge81.2019.5.1.26587', '2019-01-01 00:00:00.0', 0, 1, 'C', '2019-01-01 00:00:00.0', NULL, 0, 13, 'arresto da tre a sei mesi', NULL, 'DD', '1', 
'Quando, anche a seguito della valutazione effettuata in conformità all’articolo 28, risultano rischi che non possono essere evitati o sufficientemente limitati con misure, metodi, ovvero sistemi di organizzazione del lavoro, o con mezzi tecnici di protezione collettiva, il datore di lavoro fa ricorso alla segna', 
'Datori di lavoro e dirigenti', '7862.44', '3071.27', NULL, NULL, NULL, NULL, 'Articolo 165-1-a', 'Ammenda da 3071,27 a 7862,44', 'Legge81.2019.5.1_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81.2019M.5.1.26587_V0', 'Modified by hand in Dictionary', '26587163', 'phi-dev', 0, 'Obblighi del datore di lavoro', '163 - 1 - - Obblighi del datore di lavoro', NULL, NULL, NULL, NULL, 'Legge81.2019M.5.1.26587', '2019-01-01 00:00:00.0', 0, 1, 'C', '2019-01-01 00:00:00.0', NULL, 0, 13, 'arresto da tre a sei mesi', NULL, 'DD', '1', 
'Quando, anche a seguito della valutazione effettuata in conformità all’articolo 28, risultano rischi che non possono essere evitati o sufficientemente limitati con misure, metodi, ovvero sistemi di organizzazione del lavoro, o con mezzi tecnici di protezione collettiva, il datore di lavoro fa ricorso alla segna', 
'Datori di lavoro e dirigenti', '8577.20', '3350.47', NULL, NULL, NULL, NULL, 'Articolo 165-1-a', 'Ammenda da 3350,47 a 8577,20', 'Legge81.2019M.5.1_V0', NULL);

INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81.2019.5.1.26587_V0', (SELECT max(id) from revinfo r), 0, 'Modified by hand in Dictionary', '26587163', 'phi-dev', 0, 'Obblighi del datore di lavoro', '163 - 1 - - Obblighi del datore di lavoro', NULL, NULL, NULL, NULL, 'Legge81.2019.5.1.26587', '2019-01-01 00:00:00.0', 0, 1, 'C', '2019-01-01 00:00:00.0', NULL, 0, 13, 'arresto da tre a sei mesi', NULL, 'DD', '1', 
'Quando, anche a seguito della valutazione effettuata in conformità all’articolo 28, risultano rischi che non possono essere evitati o sufficientemente limitati con misure, metodi, ovvero sistemi di organizzazione del lavoro, o con mezzi tecnici di protezione collettiva, il datore di lavoro fa ricorso alla segna', 
'Datori di lavoro e dirigenti', '7862.44', '3071.27', NULL, NULL, NULL, NULL, 'Articolo 165-1-a', 'Ammenda da 3071,27 a 7862,44', 'Legge81.2019.5.1_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81.2019M.5.1.26587_V0', (SELECT max(id) from revinfo r), 0, 'Modified by hand in Dictionary', '26587163', 'phi-dev', 0, 'Obblighi del datore di lavoro', '163 - 1 - - Obblighi del datore di lavoro', NULL, NULL, NULL, NULL, 'Legge81.2019M.5.1.26587', '2019-01-01 00:00:00.0', 0, 1, 'C', '2019-01-01 00:00:00.0', NULL, 0, 13, 'arresto da tre a sei mesi', NULL, 'DD', '1', 
'Quando, anche a seguito della valutazione effettuata in conformità all’articolo 28, risultano rischi che non possono essere evitati o sufficientemente limitati con misure, metodi, ovvero sistemi di organizzazione del lavoro, o con mezzi tecnici di protezione collettiva, il datore di lavoro fa ricorso alla segna', 
'Datori di lavoro e dirigenti', '8577.20', '3350.47', NULL, NULL, NULL, NULL, 'Articolo 165-1-a', 'Ammenda da 3350,47 a 8577,20', 'Legge81.2019M.5.1_V0', NULL);
