delete from cessione_imp;
delete from impianti_document;
delete from scheda_generatori;
delete from scheda_generatori_indiv;
delete from scheda_recipienti_indiv;
delete from scheda_tubazioni_indiv;
delete from scheda_vasi;
delete from tariffario;
delete from alfresco_document where internal_id in (select internal_id from z_Addebito_AlfrescoDocument );
delete from z_Addebito_AlfrescoDocument;
delete from addebito;
delete from alfresco_document where internal_id in (select internal_id from z_VerificaImp_AlfrescoDocument );
delete from z_VerificaImp_AlfrescoDocument;
delete from VerificaImp_tipoProva ;
delete from verifica_imp;
delete from imp_monta;
delete from ImpPress_caratteristiche ;
delete from alfresco_document where internal_id in (select internal_id from z_ImpPress_AlfrescoDocument );
delete from z_ImpPress_AlfrescoDocument;
delete from imp_press;
delete from imp_risc;
delete from imp_search_collector;
delete from imp_soll;
delete from alfresco_document where internal_id in (select internal_id from z_ImpTerra_AlfrescoDocument );
delete from z_ImpTerra_AlfrescoDocument;
delete from imp_terra;
delete from sedi_addebito_indirizzo_sped;
update sedi_addebito set indirizzo_sped_princ_id=null;
Delete from sedi_indirizzo_sped;
delete from indirizzo_sped;
update sedi_installazione set sedi_installazione_orig_id =null;
delete from sedi_installazione;
update attivita_istat set sedi_id=null where sedi_id in (select internal_id from sedi  WHERE persona_giuridica_id in (select internal_id from persone_giuridiche where app='ARPAV'));
update cariche set sede_id=null where sede_id in (select internal_id from sedi  WHERE persona_giuridica_id in (select internal_id from persone_giuridiche where app='ARPAV'));
update ruoli set sedi_id=null where sedi_id in (select internal_id from sedi  WHERE persona_giuridica_id in (select internal_id from persone_giuridiche where app='ARPAV'));
delete from  sedi  WHERE persona_giuridica_id in (select internal_id from persone_giuridiche where app='ARPAV');
update sedi_addebito set persona_giuridica_id=null where persona_giuridica_id in (select internal_id from persone_giuridiche where app='ARPAV');
update attivita_istat set persone_giuridiche_id=null where persone_giuridiche_id in (select internal_id from persone_giuridiche where app='ARPAV');
delete from alfresco_document where PersoneGiuridiche_id in (select internal_id from persone_giuridiche where app='ARPAV' );
delete from persone_giuridiche where app='ARPAV';

delete from z_cessione_imp;
delete from z_impianti_document;
delete from z_scheda_generatori;
delete from z_scheda_generatori_indiv;
delete from z_scheda_recipienti_indiv;
delete from z_scheda_tubazioni_indiv;
delete from z_scheda_vasi;
delete from z_tariffario;
delete from z_alfresco_document where internal_id in (select internal_id from z_Addebito_AlfrescoDocument );
delete from z_Addebito_AlfrescoDocument;
delete from z_addebito;
delete from z_alfresco_document where internal_id in (select internal_id from z_VerificaImp_AlfrescoDocument );
delete from z_VerificaImp_AlfrescoDocument;
delete from z_VerificaImp_tipoProva ;
delete from z_verifica_imp;
delete from z_imp_monta;
delete from z_ImpPress_caratteristiche ;
delete from z_alfresco_document where internal_id in (select internal_id from z_ImpPress_AlfrescoDocument );
delete from z_ImpPress_AlfrescoDocument;
delete from z_imp_press;
delete from z_imp_risc;
delete from z_imp_search_collector;
delete from z_imp_soll;
delete from z_alfresco_document where internal_id in (select internal_id from z_ImpTerra_AlfrescoDocument );
delete from z_ImpTerra_AlfrescoDocument;
delete from z_imp_terra;
delete from z_sedi_addebito_indirizzo_sped;
update z_sedi_addebito set indirizzo_sped_princ_id=null;
Delete from z_sedi_indirizzo_sped;
delete from z_indirizzo_sped;
update z_sedi_installazione set sedi_installazione_orig_id =null;
delete from z_sedi_installazione;
update z_attivita_istat set sedi_id=null where sedi_id in (select internal_id from z_sedi  WHERE persona_giuridica_id in (select internal_id from z_persone_giuridiche where app='ARPAV'));
update z_cariche set sede_id=null where sede_id in (select internal_id from z_sedi  WHERE persona_giuridica_id in (select internal_id from z_persone_giuridiche where app='ARPAV'));
update z_ruoli set sedi_id=null where sedi_id in (select internal_id from z_sedi  WHERE persona_giuridica_id in (select internal_id from z_persone_giuridiche where app='ARPAV'));
delete from  z_sedi  WHERE persona_giuridica_id in (select internal_id from z_persone_giuridiche where app='ARPAV');
update z_sedi_addebito set persona_giuridica_id=null where persona_giuridica_id in (select internal_id from z_persone_giuridiche where app='ARPAV');
update z_attivita_istat set persone_giuridiche_id=null where persone_giuridiche_id in (select internal_id from z_persone_giuridiche where app='ARPAV');
delete from alfresco_document where PersoneGiuridiche_id in (select internal_id from persone_giuridiche where app='ARPAV' );
delete from z_persone_giuridiche where app='ARPAV';