-- Creazione nuovo Code SYSTEM

INSERT INTO code_system
(authority_description, authority_name, code_value_class, contact_information, creation_date, description, display_name, oid, iso_code_lang, name, revised_date, statusDB, valid_from, valid_to, version)
VALUES('GPI SpA', 'GPI SpA', 'CodeValueLaw', 'info@gpi.it', '2022-01-01 00:00:00.0', 'Fattispecie legge 81 per sospensione', 'Legge81Fattispecie', 'Legge81Fattispecie', 'it', 'Legge81Fattispecie', NULL, 1, '2022-01-01 00:00:00.0', NULL, 0);
INSERT INTO z_code_system
(id, REV, REVTYPE, authority_description, authority_name, code_value_class, contact_information, creation_date, description, display_name, oid, iso_code_lang, name, revised_date, statusDB, valid_from, valid_to, version)
VALUES(17, (SELECT max(id) from revinfo r), 0, 'GPI SpA', 'GPI SpA', 'CodeValueLaw', 'info@gpi.it', '2022-01-01 00:00:00.0', 'Fattispecie legge 81 per sospensione', 'Legge81Fattispecie', 'Legge81Fattispecie', 'it', 'Legge81Fattispecie', NULL, 1, '2022-01-01 00:00:00.0', NULL, 0);

-- Creazione top level domain
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp_V0', 'New dictionary item', '-', 'phi-dev', 0, NULL, 'Fattispecie', NULL, NULL, NULL, 'Fattispecie', 'Legge81Fattispecie.fattisp', '2022-01-01 00:00:00.0', 0, 1, 'T', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp_V0', (SELECT max(id) from revinfo r), 0, 'New dictionary item', '-', 'phi-dev', 0, NULL, 'Fattispecie', NULL, NULL, NULL, 'Fattispecie', 'Legge81Fattispecie.fattisp', '2022-01-01 00:00:00.0', 0, 1, 'T', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Creazione foglie
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.01_V0', 'Modified by hand in Dictionary', '01', 'phi-dev', 0, 'Mancata elaborazione del documento di valutazione dei rischi ', '01 Mancata elaborazione del documento di valutazione dei rischi ', NULL, NULL, NULL, '1 Mancata elaborazione del documento di valutazione dei rischi ', 'Legge81Fattispecie.fattisp.01', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.02_V0', 'Added updating dictionary', '02', 'phi-dev', 0, 'Mancata elaborazione del Piano di Emergenza ed evacuazione', '02 Mancata elaborazione del Piano di Emergenza ed evacuazione', NULL, NULL, NULL, '2 Mancata elaborazione del Piano di Emergenza ed evacuazione', 'Legge81Fattispecie.fattisp.02', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.03_V0', 'Added updating dictionary', '03', 'phi-dev', 0, 'Mancata formazione ed addestramento', '03 Mancata formazione ed addestramento', NULL, NULL, NULL, '3 Mancata formazione ed addestramento', 'Legge81Fattispecie.fattisp.03', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '300', '300', NULL, 'lav', NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.04_V0', 'Added updating dictionary', '04', 'phi-dev', 0, 'Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', '04 Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', NULL, NULL, NULL, '4 Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', 'Legge81Fattispecie.fattisp.04', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.05_V0', 'Added updating dictionary', '05', 'phi-dev', 0, 'Mancata elaborazione piano operativo di sicurezza (POS)', '05 Mancata elaborazione piano operativo di sicurezza (POS) ', NULL, NULL, NULL, '5 Mancata elaborazione piano operativo di sicurezza (POS) ', 'Legge81Fattispecie.fattisp.05', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.06_V0', 'Added updating dictionary', '06', 'phi-dev', 0, 'Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', '06 Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', NULL, NULL, NULL, '6 Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', 'Legge81Fattispecie.fattisp.06', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '300', '300', NULL, 'lav', NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.07_V0', 'Added updating dictionary', '07', 'phi-dev', 0, 'Mancanza di protezioni verso il vuoto', '07 Mancanza di protezioni verso il vuoto', NULL, NULL, NULL, '7 Mancanza di protezioni verso il vuoto', 'Legge81Fattispecie.fattisp.07', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.08_V0', 'Modified by hand in Dictionary', '08', 'phi-dev', 0, 'Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', '08 Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', NULL, NULL, NULL, '8 Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', 'Legge81Fattispecie.fattisp.08', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.09_V0', 'Added updating dictionary', '09', 'phi-dev', 0, 'Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', '09 Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', NULL, NULL, NULL, '9 Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', 'Legge81Fattispecie.fattisp.09', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.10_V0', 'Added updating dictionary', '10', 'phi-dev', 0, 'Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', '10 Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', NULL, NULL, NULL, '10 Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', 'Legge81Fattispecie.fattisp.10', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.11_V0', 'Modified by hand in Dictionary', '11', 'phi-dev', 0, 'Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore magnetotermico, interruttore differenziale)', '11 Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore magnetotermico, interruttore differenziale)', NULL, NULL, NULL, '11 Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore magnetotermico, interruttore differenziale)', 'Legge81Fattispecie.fattisp.11', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.12b_V0', 'Added updating dictionary', '12b', 'phi-dev', 0, 'Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', '12bis Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', NULL, NULL, NULL, '12-bis Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', 'Legge81Fattispecie.fattisp.12b', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO code_value_law
(id, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.12_V0', 'Added updating dictionary', '12', 'phi-dev', 0, 'Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', '12 Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', NULL, NULL, NULL, '12 Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', 'Legge81Fattispecie.fattisp.12', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);

INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.01_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '01', 'phi-dev', 0, 'Mancata elaborazione del documento di valutazione dei rischi', '01 Mancata elaborazione del documento di valutazione dei rischi ', NULL, NULL, NULL, '1 Mancata elaborazione del documento di valutazione dei rischi ', 'Legge81Fattispecie.fattisp.01', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.02_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '02', 'phi-dev', 0, 'Mancata elaborazione del Piano di Emergenza ed evacuazione', '02 Mancata elaborazione del Piano di Emergenza ed evacuazione', NULL, NULL, NULL, '2 Mancata elaborazione del Piano di Emergenza ed evacuazione', 'Legge81Fattispecie.fattisp.02', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.03_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '03', 'phi-dev', 0, 'Mancata formazione ed addestramento', '03 Mancata formazione ed addestramento', NULL, NULL, NULL, '3 Mancata formazione ed addestramento', 'Legge81Fattispecie.fattisp.03', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '300', '300', NULL, 'lav', NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.04_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '04', 'phi-dev', 0, 'Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', '04 Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', NULL, NULL, NULL, '4 Mancata costituzione del servizio di prevenzione e protezione e nomina del relativo responsabile', 'Legge81Fattispecie.fattisp.04', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.05_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '05', 'phi-dev', 0, 'Mancata elaborazione piano operativo di sicurezza (POS)', '05 Mancata elaborazione piano operativo di sicurezza (POS) ', NULL, NULL, NULL, '5 Mancata elaborazione piano operativo di sicurezza (POS) ', 'Legge81Fattispecie.fattisp.05', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '2500', '2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.06_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '06', 'phi-dev', 0, 'Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', '06 Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', NULL, NULL, NULL, '6 Mancata fornitura del dispositivo di protezione individuale contro le cadute dall''alto', 'Legge81Fattispecie.fattisp.06', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '300', '300', NULL, 'lav', NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.07_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '07', 'phi-dev', 0, 'Mancanza di protezioni verso il vuoto', '07 Mancanza di protezioni verso il vuoto', NULL, NULL, NULL, '7 Mancanza di protezioni verso il vuoto', 'Legge81Fattispecie.fattisp.07', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.08_V0', (SELECT max(id) from revinfo r), 1, 'Added updating dictionary', '08', 'phi-dev', 0, 'Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', '08 Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', NULL, NULL, NULL, '8 Mancata applicazione delle armature di sostegno, fatte salve le prescrizioni desumibili dalla relazione tecnica di consistenza del terreno', 'Legge81Fattispecie.fattisp.08', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.09_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '09', 'phi-dev', 0, 'Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', '09 Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', NULL, NULL, NULL, '9 Lavori in prossimità di linee elettriche in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', 'Legge81Fattispecie.fattisp.09', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.10_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '10', 'phi-dev', 0, 'Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', '10 Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', NULL, NULL, NULL, '10 Presenza di conduttori nudi in tensione in assenza di disposizioni organizzative e procedurali idonee a proteggere i lavoratori dai conseguenti rischi', 'Legge81Fattispecie.fattisp.10', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.11_V0', (SELECT max(id) from revinfo r), 1, 'Added updating dictionary', '11', 'phi-dev', 0, 'Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore 
magnetotermico, interruttore differenziale)', '11 Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore magnetotermico, interruttore differenziale)', NULL, NULL, NULL, '11 Mancanza di protezione contro i contatti diretti ed indiretti (impianto di terra, interruttore magnetotermico, interruttore differenziale)', 'Legge81Fattispecie.fattisp.11', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.12b_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '12b', 'phi-dev', 0, 'Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', '12bis Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', NULL, NULL, NULL, '12-bis Mancata notifica all’organo di vigilanza prima dell’inizio dei lavori che possono comportare il rischio di esposizione all’amianto', 'Legge81Fattispecie.fattisp.12b', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);
INSERT INTO z_code_value_law
(id, REV, REVTYPE, change_reason, code, creator, default_child, description, display_name, keywords, lang_de, lang_en, lang_it, oid, revised_date, sequence_number, statusDB, typeDB, valid_from, valid_to, version, code_system, arresto, classificazione, codice_contravventore, comma, corpo, descrizione_contravventore, importo_max, importo_min, lettera, nota_contravventore, nota_prescrizione, nota_violazione, sanzionato_da, sanzione, code_value_parent, numero)
VALUES('Legge81Fattispecie.fattisp.12_V0', (SELECT max(id) from revinfo r), 0, 'Added updating dictionary', '12', 'phi-dev', 0, 'Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', '12 Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', NULL, NULL, NULL, '12 Omessa vigilanza in ordine alla rimozione o modifica dei dispositivi di sicurezza o di segnalazione o di controllo', 'Legge81Fattispecie.fattisp.12', '2022-01-01 00:00:00.0', 0, 1, 'C', '2022-01-01 00:00:00.0', NULL, 0, 17, NULL, NULL, NULL, NULL, NULL, NULL, '3000', '3000', NULL, NULL, NULL, NULL, NULL, NULL, 'Legge81Fattispecie.fattisp_V0', NULL);


