--Update tabelle Portale notifica cantieri

DROP TABLE IF EXISTS `pnc_cantiere`;
CREATE TABLE  `pnc_cantiere` (
  `internal_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_by` varchar(255) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  `addr_adl` varchar(255) DEFAULT NULL,
  `addr_bnr` varchar(255) DEFAULT NULL,
  `addr_cen` varchar(255) DEFAULT NULL,
  `addr_cnt` varchar(255) DEFAULT NULL,
  `addr_cpa` varchar(255) DEFAULT NULL,
  `addr_cty` varchar(255) DEFAULT NULL,
  `addr_sta` varchar(255) DEFAULT NULL,
  `addr_stb` varchar(255) DEFAULT NULL,
  `addr_str` varchar(255) DEFAULT NULL,
  `addr_zip` varchar(255) DEFAULT NULL,
  `cost` double DEFAULT NULL,
  `data_comunicazione` datetime DEFAULT NULL,
  `durata_lavori` int(11) DEFAULT NULL,
  `inizio_lavori` datetime DEFAULT NULL,
  `max_workers` int(11) DEFAULT NULL,
  `natura_opera` varchar(1000) DEFAULT NULL,
  `numero_imprese` int(11) DEFAULT NULL,
  `addr_code` varchar(255) DEFAULT NULL,
  `pec_recipient` varchar(255) DEFAULT NULL,
  `pec_sender` varchar(255) DEFAULT NULL,
  `created_user` varchar(255) DEFAULT NULL,
  `id_parent` bigint(20) DEFAULT NULL,
  `pdf_bcode` longblob,
  PRIMARY KEY (`internal_id`),
  KEY `FKCF62E5CDF89489A8` (`addr_code`),
  KEY `id_parent` (`id_parent`),
  CONSTRAINT `FKCF62E5CDF89489A8` FOREIGN KEY (`addr_code`) REFERENCES `code_value_city` (`id`),
  CONSTRAINT `pnc_cantiere_ibfk_1` FOREIGN KEY (`id_parent`) REFERENCES `pnc_cantiere` (`internal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `pnc_ditte_cantiere`;
CREATE TABLE  `pnc_ditte_cantiere` (
  `internal_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_by` varchar(255) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  `codice_fiscale` varchar(255) DEFAULT NULL,
  `denominazione` varchar(255) DEFAULT NULL,
  `partita_iva` varchar(255) DEFAULT NULL,
  `cantiere_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`internal_id`),
  KEY `FK_PND_cantiere` (`cantiere_id`),
  KEY `IX_PND_cantiere` (`cantiere_id`),
  CONSTRAINT `FK_PND_cantiere` FOREIGN KEY (`cantiere_id`) REFERENCES `pnc_cantiere` (`internal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `pnc_persone_cantiere`;
CREATE TABLE  `pnc_persone_cantiere` (
  `internal_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_by` varchar(255) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `version` bigint(20) DEFAULT NULL,
  `addr_adl` varchar(255) DEFAULT NULL,
  `addr_bnr` varchar(255) DEFAULT NULL,
  `addr_cen` varchar(255) DEFAULT NULL,
  `addr_cnt` varchar(255) DEFAULT NULL,
  `addr_cpa` varchar(255) DEFAULT NULL,
  `addr_cty` varchar(255) DEFAULT NULL,
  `addr_sta` varchar(255) DEFAULT NULL,
  `addr_stb` varchar(255) DEFAULT NULL,
  `addr_str` varchar(255) DEFAULT NULL,
  `addr_zip` varchar(255) DEFAULT NULL,
  `codice_fiscale` varchar(255) DEFAULT NULL,
  `name_del` varchar(255) DEFAULT NULL,
  `name_fam` varchar(255) DEFAULT NULL,
  `name_formatted` varchar(255) DEFAULT NULL,
  `name_giv` varchar(255) DEFAULT NULL,
  `name_pfx` varchar(255) DEFAULT NULL,
  `name_sfx` varchar(255) DEFAULT NULL,
  `addr_code` varchar(255) DEFAULT NULL,
  `cantiere_id` bigint(20) DEFAULT NULL,
  `ruolo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`internal_id`),
  KEY `FK_PNC_ruolo` (`ruolo`),
  KEY `FK36BD737CF89489A8` (`addr_code`),
  KEY `FK_PNCPC_cantiere` (`cantiere_id`),
  KEY `IX_PNCPC_cantiere` (`cantiere_id`),
  KEY `IX_PNC_ruolo` (`ruolo`),
  CONSTRAINT `FK36BD737CF89489A8` FOREIGN KEY (`addr_code`) REFERENCES `code_value_city` (`id`),
  CONSTRAINT `FK_PNCPC_cantiere` FOREIGN KEY (`cantiere_id`) REFERENCES `pnc_cantiere` (`internal_id`),
  CONSTRAINT `FK_PNC_ruolo` FOREIGN KEY (`ruolo`) REFERENCES `code_value` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;