package com.phi.rest.datamodel;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Flotr2 graph datamodel
 * See http://www.humblesoftware.com/flotr2/
 * 
 * To add options, see documentation: 
 * http://www.humblesoftware.com/flotr2/documentation
 * 
 * @author Alex
 */
public class GraphDatamodel {
	
	public List<Serie> series = new ArrayList<Serie>();
	public Options options = new Options();

	public class Serie {
		public String label;
		public boolean hideLabelInLegend = false; //Added to FLOTR2 by AZ
		public List<Object> data;
		public Map<String, Object> lines;
		public Map<String, Object> points;
		public Map<String, Object> timeline;
		public Map<String, Object> markers;
		public Long yPosition;
		public Integer xaxis; // 1: button 2: top
		public Integer yaxis; // 1: left 2: right
		public String color;
		
		public String unitOfMeasure; //not flotr2 field
		public Double minValue; //not flotr2 field
		public Double maxValue; //not flotr2 field
	}
	
	public class Options {
		
		public Axis xaxis = new Axis();
		public Axis x2axis = new Axis();
		public Axis yaxis = new Axis();
		public Axis y2axis = new Axis();
		
		public class Axis {
			public Double max;
			public Double min;
			public String mode;
			public String timeMode;
			public List ticks; //type can be array or long
			public List minorTicks;
			public Boolean autoscale;      // Default False, Turns autoscaling on with true
			//public Integer autoscaleMargin; // Default 0, margin in % to add if auto-setting min/max
//			public int noTicks;  //number of ticks for automagically generated ticks, default 5
//			public int minorTickFreq;  //number of minor ticks between major ticks for autogenerated ticks
		}
	}
}