package com.phi.entities.baseEntity;

// Generated 15-lug-2015 13.47.19 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.annotations.Index;
import org.hibernate.envers.Audited;

/**
 * Sopralluoghi generated by hbm2java
 */

import com.phi.entities.baseEntity.BaseEntity;
import com.phi.entities.baseEntity.Attivita;
import com.phi.entities.dataTypes.CodeValue;
import com.phi.entities.dataTypes.CodeValuePhi;

@Entity
@Table(name = "accesso_atti")
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@Audited
public class AccessoAtti extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2458582425234307502L;


	/**
	*  javadoc for attivita
	*/
	private Attivita attivita;

	@OneToOne(fetch=FetchType.LAZY, mappedBy="accessoAtti", cascade=CascadeType.PERSIST)
	public Attivita getAttivita(){
		return attivita;
	}

	public void setAttivita(Attivita attivita){
		this.attivita = attivita;
	}


	@Override
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "Accesso_sequence")
	@SequenceGenerator(name = "Accesso_sequence", sequenceName = "Accesso_sequence")
	@Column(name = "internal_id")
	public long getInternalId() {
		return internalId;
	}
	
	@Override
	public void setInternalId(long internalId) {
		this.internalId = internalId;
	}
	
	private CodeValue richiedenteCv;

	@ManyToOne(fetch=FetchType.LAZY, targetEntity=CodeValuePhi.class)
    @JoinColumn(name="richiedente_cv")
	@ForeignKey(name="FK_Acc_riccv")
	//@Index(name="IX_Acc_riccv")
	public CodeValue getRichiedenteCv() {
		return richiedenteCv;
	}
	
	public void setRichiedenteCv(CodeValue richiedenteCv) {
		this.richiedenteCv = richiedenteCv;
	}
	
	private String richiedente;
	
	@Column(name = "richiedente")
	public String getRichiedente() {
		return this.richiedente;
	}

	public void setRichiedente(String richiedente) {
		this.richiedente = richiedente;
	}
	

}
