package com.phi.entities.baseEntity;

// Generated 15-lug-2015 13.47.19 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;

import org.hibernate.annotations.ForeignKey;
import org.hibernate.annotations.Index;
import org.hibernate.envers.Audited;

/**
 * Sopralluoghi generated by hbm2java
 */

import com.phi.entities.baseEntity.BaseEntity;
import com.phi.entities.baseEntity.Attivita;
import com.phi.entities.dataTypes.CodeValue;
import com.phi.entities.dataTypes.CodeValuePhi;
import com.phi.entities.role.Person;
import com.phi.entities.baseEntity.Sedi;
import com.phi.entities.baseEntity.PersoneGiuridiche;

@Entity
@Table(name = "sequestri")
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@Audited
public class Sequestri extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9221204043024553216L;

	/**
	*  javadoc for custodeGiudiziario
	*/
	private Person custodeGiudiziario;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="custode_giudiziario_id")
	@ForeignKey(name="FK_Squstri_custodGidiziario")
	//@Index(name="IX_Squstri_custodGidiziario")
	public Person getCustodeGiudiziario(){
		return custodeGiudiziario;
	}

	public void setCustodeGiudiziario(Person custodeGiudiziario){
		this.custodeGiudiziario = custodeGiudiziario;
	}

	private CodeValue proprietario;

	@ManyToOne(fetch=FetchType.LAZY, targetEntity=CodeValuePhi.class)
    @JoinColumn(name="proprietario")
	@ForeignKey(name="FK_Seq_prop")
	//@Index(name="IX_Seq_prop")
	public CodeValue getProprietario() {
		return proprietario;
	}
	
	public void setProprietario(CodeValue proprietario) {
		this.proprietario = proprietario;
	}
	
	/**
	*  javadoc for proprietarioUtente
	*/
	private Person proprietarioUtente;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="proprietario_persona_id")
	@ForeignKey(name="FK_Sqstri_propritarioPrsona")
	//@Index(name="IX_Sqstri_propritarioPrsona")
	public Person getProprietarioUtente(){
		return proprietarioUtente;
	}

	public void setProprietarioUtente(Person proprietarioUtente){
		this.proprietarioUtente = proprietarioUtente;
	}

	/**
	*  javadoc for proprietarioDitta
	*/
	private PersoneGiuridiche proprietarioDitta;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="proprietario_ditta_id")
	@ForeignKey(name="FK_Squstri_propritarioDitta")
	//@Index(name="IX_Squstri_propritarioDitta")
	public PersoneGiuridiche getProprietarioDitta(){
		return proprietarioDitta;
	}

	public void setProprietarioDitta(PersoneGiuridiche proprietarioDitta){
		this.proprietarioDitta = proprietarioDitta;
	}

	/**
	*  javadoc for proprietarioSede
	*/
	private Sedi proprietarioSede;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="proprietario_sede_id")
	@ForeignKey(name="FK_Sequestri_proprietarioSd")
	//@Index(name="IX_Sequestri_proprietarioSd")
	public Sedi getProprietarioSede(){
		return proprietarioSede;
	}

	public void setProprietarioSede(Sedi proprietarioSede){
		this.proprietarioSede = proprietarioSede;
	}

	@Override
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "Sequestri_sequence")
	@SequenceGenerator(name = "Sequestri_sequence", sequenceName = "Sequestri_sequence")
	@Column(name = "internal_id")
	public long getInternalId() {
		return internalId;
	}
	
	@Override
	public void setInternalId(long internalId) {
		this.internalId = internalId;
	}
	
	private CodeValue tipoSequestro;

	@ManyToOne(fetch=FetchType.LAZY, targetEntity=CodeValuePhi.class)
    @JoinColumn(name="tipo_sequestro")
	@ForeignKey(name="FK_Seq_type")
	//@Index(name="IX_Seq_type")
	public CodeValue getTipoSequestro() {
		return tipoSequestro;
	}

	public void setTipoSequestro(CodeValue tipoSequestro) {
		this.tipoSequestro = tipoSequestro;
	}
	
	private String attivitaSvolta;
	
	@Column(name = "attivita_svolta")
	public String getAttivitaSvolta() {
		return this.attivitaSvolta;
	}

	public void setAttivitaSvolta(String attivitaSvolta) {
		this.attivitaSvolta = attivitaSvolta;
	}
	
	private String oggetto;
	
	@Column(name = "oggetto")
	public String getOggetto() {
		return this.oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	private boolean convalida;
	
	@Column(name="convalida")
	public boolean getConvalida() {
		return convalida;
	}

	public void setConvalida(boolean convalida) {
		this.convalida = convalida;
	}	
	
	private boolean ulterioriAccertamenti;
	
	@Column(name="ulteriori_accertamenti")
	public boolean getUlterioriAccertamenti() {
		return ulterioriAccertamenti;
	}

	public void setUlterioriAccertamenti(boolean ulterioriAccertamenti) {
		this.ulterioriAccertamenti = ulterioriAccertamenti;
	}
	
	private boolean sicurezza;
	
	@Column(name="sicurezza")
	public boolean getSicurezza() {
		return sicurezza;
	}

	public void setSicurezza(boolean sicurezza) {
		this.sicurezza = sicurezza;
	}

	private Date dataRichiesta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_richiesta")
	public Date getDataRichiesta(){
		return dataRichiesta;
	}

	public void setDataRichiesta(Date dataRichiesta){
		this.dataRichiesta = dataRichiesta;
	}

	private String allegati;
	
	@Column(name = "allegati")
	public String getAllegati() {
		return this.allegati;
	}

	public void setAllegati(String allegati) {
		this.allegati = allegati;
	}
	
	private String conclusioni;
	
	@Column(name = "conclusioni")
	public String getConclusioni() {
		return this.conclusioni;
	}

	public void setConclusioni(String conclusioni) {
		this.conclusioni = conclusioni;
	}
	
	private boolean confinamento;
	
	@Column(name="confinamento")
	public boolean getConfinamento() {
		return confinamento;
	}

	public void setConfinamento(boolean confinamento) {
		this.confinamento = confinamento;
	}
	
	private boolean sigilli;
	
	@Column(name="sigilli")
	public boolean getSigilli() {
		return sigilli;
	}

	public void setSigilli(boolean sigilli) {
		this.sigilli = sigilli;
	}	
	
	private boolean custodia;
	
	@Column(name="custodia")
	public boolean getCustodia() {
		return custodia;
	}

	public void setCustodia(boolean custodia) {
		this.custodia = custodia;
	}
	
	private Date dataRestituzione;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_restituzione")
	public Date getDataRestituzione(){
		return dataRestituzione;
	}

	public void setDataRestituzione(Date dataRestituzione){
		this.dataRestituzione = dataRestituzione;
	}

}
