<#macro Widget w>
<#if w.type == "Label"><#if !w.dgBodyEntityName??>
${""?left_pad(w.depth*2)}<div class="lbl"<#if w.rendered??> *ngIf="${w.rendered}"</#if>>
</#if><#if w.widgetLabel??>${""?left_pad(w.depth*2)}<label>{{'label_${w.id}' | translate}}</label>
</#if>${""?left_pad(w.depth*2)}<span<#if w.dgBodyEntityName??><#if w.rendered??> *ngIf="${w.rendered}"</#if></#if><#if w.styleClass??> class="${w.styleClass}"</#if><#if w.jollyParameter??> ${w.jollyParameter}</#if>><#if w.binding??>{{${w.binding}<#if w.dateTimePattern??> | dateFormat: '${w.dateTimePattern}'</#if>}}</#if><#if w.value??>{{'${w.id}' | translate}}</#if><#if w.valueEL??>{{${w.valueEL}}}</#if></span><#if !w.dgBodyEntityName??>
${""?left_pad(w.depth*2)}</div></#if>
<#elseif w.type == "JollyWidget">
${""?left_pad(w.depth*2)}${w.value}
<#else>
${""?left_pad(w.depth*2)}<phi-${w.type?lower_case}<#if w.type=="Link" || w.type?starts_with("Button")><#if w.binding??> (binding)="${w.binding}"</#if> id="${w.id}"<#else><#if w.binding??> [(ngModel)]="${w.binding}"<#if w.dgBodyEntityName??> [name]="'${w.binding}'+i"<#else> name="${w.binding}"</#if></#if> id="${w.id}"</#if><#if w.bindingHigh??> bindingHigh="${w.bindingHigh}"</#if><#if w.mnemonicName??> mnemonicName="${w.mnemonicName}"</#if><#if w.widgetLabel??> [widgetLabel]="'label_${w.id}' | translate"</#if><#if w.x??> x="${w.x?c}"</#if><#if w.y??> y="${w.y?c}"</#if><#if w.width??> width="${w.width?c}"</#if><#if w.height??> height="${w.height?c}"</#if><#if w.styleClass??> styleClass="${w.styleClass}"</#if><#if w.tooltip??> tooltip="{{'alt_${w.id}' | translate}}"</#if><#if w.domain??> domain="${w.domain}"</#if><#if w.listElementsExpression??> [listElementsExpression]="${w.listElementsExpression}"</#if><#if w.customCode??> customCode={() => {${w.customCode}}}</#if><#if w.required??> [required]="${w.required}"</#if><#if w.rendered??> [renderedEl]="${w.rendered}"</#if><#if w.disabled??> [disabled]="${w.disabled}"</#if><#if w.dateTimeFormat??> dateTimeFormat="${w.dateTimeFormat}"</#if><#if w.todayIsDefaultTime> todayIsDefaultTime="true"</#if><#if w.converter??> converter="${w.converter}"</#if><#if w.emptyField??> [emptyField]="'alt_${w.id}' | translate"</#if><#if w.jollyParameter??> ${w.jollyParameter}</#if><#if w.minimum??> minimum="${w.minimum}"</#if><#if w.maximum??> maximum="${w.maximum}"</#if><#if w.defaultValue??> defaultValue="${w.defaultValue}"</#if><#if w.layout??> layout="${w.layout}"</#if>><#if w.iconClass??><i class="${w.iconClass}"></i></#if><#if w.value??>{{'${w.id}' | translate}}</#if><#if w.valueEL??>{{${w.valueEL}}}</#if></phi-${w.type?lower_case}>
</#if>
</#macro>