export const environment = {
  production: true,
  hmr: false,
  apiUrl: '/PHI_CI/',
  languages: [['it', 'Italiano']/*, ['en', 'English']*/, ['de', 'Deutsch']],
  home: 'dashboard/adt',
  banner: {
    showPolicy:false,
    showCVC: true,
    startProcess: undefined,
    showLanguage: false,
    showAllergy: true,
    showConsent: false,
    showEncounter: true,
    showExtraInfo: false,
    confirmLogout: true,
    ieRepositoryViewer: true
  },
  manu: {
    processes: []
  },
  openMenuAtHome: true,
  ambulatoryCalendar: {
    rootCtrl: true,
    alterColor: false,
    viewTherapist: false,
    useRead: true,
    startHour: 7,
    endHour: 21,
    startWorkHour: 8,
    endWorkHour: 20,
    minutesPerRow: 5,
    minutesPerRowShort: 5,
    minutesPerRowMedium: 15,
    minutesPerRowLong: 60,
    pixelPerMinute: 4,
    moveSdl: false,
    saveFavoriteSdl: false,
    showPerformedProcedure: false,
    report: undefined,
    prefixedDuration: true,
    defaultDurationColor: false,
    dblClickProcess: undefined,
    loadIsPsychooncology: true,
    colorizeHolidays: true,
    updateInternalActivitySdl: true,
    columns: 8,
    timeBands: true
  },
  ambulatoryPortal: {
    priorityShow: false,
    useRead: false,
    status: 'PHIDIC:AppointmentStatus',
    sentBy: undefined,
    inChargeTable: false,
    dblClickProcess: undefined,
    showAppointmentList: true,
    showFiscalCode: true,
    useGrouperId: false,
    selectedStatuses: ['completed', 'arrived', 'visiting', 'planned', 'reported', 'nullified'],
    dateRange: false,
    requiredDeleteReason: true,
    showWaitingProcIcon: false
  },
  calendarMenu: {
    addAppointmentProcess: undefined,
    addCycleProcess: undefined,
    addIndirectProc: true,
    addActivity: true,
    addCoordination: true,
    addAppointmentNote: true,
    printColumn: true,
    addActivityWithoutProcedure: false
  },
  appointmentMenu: {
    showDetailsProcess: undefined,
    select: true,
    edit: true,
    endCycle: true,
    noteHistory: false,

    arrivedProcess: undefined,
    takeInCharge: false,
    summary: false,
    registry: false,
    history: false,
    episodeList: false,
    invoice: false,
    note: false,
    procedure: false,
    erogate: true,
    report: true,
    reputInWl: true,
    cancel: true,
    arrived: true,
    reopen: false,
    disableDeleteByRole: true,
    reportedCheck: false,
    fakeClassCode: false
  },
  appointmentEdit: {
    loadProcedureDefinitions: true
  },
  appointmentAction: {
    changeStatus: 'vco_status',
    update: '/vco_update',
    copy: '/vco_copy',
    create: '/vco_create'
  },
  adt: {
    action: 'adt',
    additionals: null,
    onlyWardChildren: false,
    showAdtWard: true,
    showAdtPatient: true,
    showAdtFilter: true,
    showAdtData: false,
    showVitalSignAlert: true,
    report: undefined,
    status: undefined,
    selectedStatuses: ['new', 'active', 'held'],
    bradenOrNorton: undefined,
    bracialetReport: true,
    searchByBarcode: true,
    table: {
      bigIcons: false,
      note: true,
      appointmentDate: false,
      chart: true,
      tempWard: true,
      clinicalDiary: true,
      discharge: true,
      dischargeletter: false,
      nurseCheck: true,
      pain: true,
      injuryRisk: true,
      fallRisk: true,
      morse: false,
      referrer: false,
      invoiceClosed: false,
      sdoClosed: false,
      anesthesistCheck: true
    },
    procedures: false,
    transfers: true,
    showWaitingProcIcon: false,
    refreshOnInit: false,
    menu: undefined
  },
  nurseActivity: {
    onlyExecutions: false,
    clinicalDiary: true,
    drugs: true
  },
  lockedNodeProcess: 'MOD_Admin/CORE/PROCESSES/lockedNodeAlert',
  sign: {
    basePath: '/scaricoFirma/',
    format: '<FontSize>6</FontSize><Text>%reason%</Text>',
    reason: 'Documento firmato digitalmente ai sensi del D.Lgs. 82/2005 e ss.mm.ii.',
    location: 'Firmato in data',
    synchro: true
  },
  reportInNewTab: false,
  checkLockedStatus: true,
  options: {
    showComment: true
  }
};
