package com.phi.entities;

import javax.persistence.Embeddable;

/**
 * UniqueCheckId generated by hbm2java
 */
@Embeddable
public class UniqueCheckId implements java.io.Serializable {

	private static final long serialVersionUID = -3757547568201890338L;

	private String root;
	private String extension;

	public UniqueCheckId() {
	}

	public UniqueCheckId(String root, String extension) {
		this.root = root;
		this.extension = extension;
	}

	public String getRoot() {
		return this.root;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((extension == null) ? 0 : extension.hashCode());
		result = prime * result + ((root == null) ? 0 : root.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UniqueCheckId other = (UniqueCheckId) obj;
		if (extension == null) {
			if (other.extension != null)
				return false;
		} else if (!extension.equals(other.extension))
			return false;
		if (root == null) {
			if (other.root != null)
				return false;
		} else if (!root.equals(other.root))
			return false;
		return true;
	}

}